### ISSUE TITLE
bin格式图片

### ISSUE THREAD

**Issue by mzy2364** [zhangjingxun12/Lvgl_image_convert_tool#1]
感谢作者，bin格式和c格式的图片显示都是OK的，bin文件格式的图片存放在外部文件系统，上电后加载到RAM进行使用

**Comment by zhangjingxun12** [comment]
正常就好，起初我用了在线转换后的bin文件，在esp32上使用，但是使用时发现有拖影，加了几层flash接口的问题，然后改为c了， 做了这个工具后也没测试了，谢谢回复和支持😁
