### ISSUE TITLE
批量转换图片

### ISSUE THREAD

**Issue by phiau** [zhangjingxun12/Lvgl_image_convert_tool#3]
你好，批量转换图片的功能在 1.0.3.0 的版本可以用吗？
我这里不能选择图片文件夹路径，只能选择图片路径。
不过可以直接调用 php 方法，来批量转换。

**Comment by zhangjingxun12** [comment]
1.0.3可以批量转换
暂时不能直接选择文件夹，但可以在选择图片的对话界面里全选（ctrl+A），会自动过滤掉非图片的文件的
